### PR TITLE
Add pre-commit hook to automatically keep track of dependencies

### LINKED ISSUE #19: Add pre-commit hook to automatically keep track of dependencies
Whenever things break from dependency issues, I have to go track down which package is at fault by manually uninstalling/reinstalling until I find the right one.  If I had a record of the dependencies associated with every commit, I could easily compare the diff to find the offender.  See [catalystneuro/datta-lab-to-nwb#58](https://github.com/catalystneuro/datta-lab-to-nwb/pull/58) for a potential solution.

### PR DESCRIPTION
**Pull request by pauladkisson**
Fixes #19

### CODE REVIEW

**Comment by h-mayorquin** [comment]
Sorry for not answering this for so long. 

Is there a way that we can have this on the repo but at the same time make it opt-in? As in, we allow these configuration to be there but there is another small change that needs to be done to get it there to run?

I don't want to generate these files every time that I commit as I don't use pip for lock files myself so I don't want this files sitting around.

Does this make sense?

**Comment by CodyCBakerPhD** [comment]
FYI from experience of this hook applied to the Datta lab, it can create some pretty consistent and nasty merge conflicts especially when multiple developers contribute to the same common package (can't see them anymore because Paul closed them, but https://github.com/catalystneuro/datta-lab-to-nwb/pull/71 and https://github.com/catalystneuro/datta-lab-to-nwb/pull/70 were fresh commits from `main` at the time, from different user on a different platform, with only minor changes performed in each)

In general I would say the proper solution to this situation is to just use poetry or a platform-specific conda environment files (Dendro uses the former, GUIDE uses the latter)

**Comment by pauladkisson** [comment]
@h-mayorquin how about this?

Also, it has been useful for me, and really not much of a burden.

**Comment by h-mayorquin** [comment]
That seems like a simple solution to me.

@CodyCBakerPhD would you be OK with it? That would facilitate Paul's workflow for his solo projects and not get in the way of others that don't want to use it.

Btw, I personally use [rye](https://rye-up.com/) for this as I never liked the poetry workflow. But there seems to be a new [push recently to standarize lock file]s(https://discuss.python.org/t/lock-files-again-but-this-time-w-sdists/46593). Fingers cross it works.

**Comment by CodyCBakerPhD** [comment]
I'm still not convinced why we should include it in the general cookie-cutter if it's just for one person, and if everyone else has a preferred way of doing it - surely Paul can just add it himself to any of his projects?

Also `pip freeze` is insufficient in conda-dependent environments (NWB Benchmarks, GUIDE) so I also don't know if we'd want to recommend this generally either

**Comment by pauladkisson** [comment]
Cool, I'll have to check out rye. Also, I proposed this for the cookie cutter because I felt like it was a handy tool worth sharing, but if no one else is going to use it because everyone has their own preferred way of keeping track of dependencies then I am more than happy to just add it to each of my projects.

**Comment by h-mayorquin** [comment]
My philosophy is that the cookiecutter should just kind of make our (the team) work easier.  This is a script more than a package so I am not that interested on building something very general here. I also don't really like using pip-freeze for lock files but if there is something that saves time for one us that seems like something work having? 

As I was writing this Paul wrote his last comment. In the light of that, if anyone else other than Paul says that this would be useful for them then I will merge.

**Comment by pauladkisson** [comment]
I was reading up on rye as well as the package [guide](https://py-pkgs.org/) that ben mentioned (which uses poetry), and I found a nice Venn diagram showing all of the different python packaging tools and their various overlapping roles: [diagram](https://alpopkes.com/posts/python/figures/venn_diagram.png).

Basically, what I'm using right now is Conda for environment management and python version management, pip for package management, setuptools for package building, and twine for package publishing. That sounds like a lot of tools, but the cookie cutter already has automated github actions for package building and package publishing, so I (so far) never have needed to interact with those. And since I already know the syntax for Conda and pip, I don't really think it will be worth my time to learn rye (though it is cool that it does all the jobs in the diagram).

I also prefer to play it fast and loose with my dependencies in a given environment. For example, if I'm making changes to the photometry extension for my photometry interface and I want to change the installation location from pypi to local to a github branch/commit and then back to pypi, it's a bit tedious to have to constantly be updating the requirements file (or pyproject.toml in the case of rye) and then generate a new lock file and then reinstall from the new lock. In contrast, with this hook I can freely change my installation of ndx-photometry directly using pip as many times as I like, and there's a faithful record in case I ever run into any dependency related bugs.

With all that being said, it doesn't look like anybody else is particularly interested in this hook, so I think we can just close this PR and continue with everyone using their own preferred dependency management solution.

**Comment by h-mayorquin** [comment]
> I also prefer to play it fast and loose with my dependencies in a given environment. For example, if I'm making changes to the photometry extension for my photometry interface and I want to change the installation location from pypi to local to a github branch/commit and then back to pypi, it's a bit tedious to have to constantly be updating the requirements file (or pyproject.toml in the case of rye) and then generate a new lock file and then reinstall from the new lock. In contrast, with this hook I can freely change my installation of ndx-photometry directly using pip as many times as I like, and there's a faithful record in case I ever run into any dependency related bugs.

Interesting. Would using a different environment for local vs remote installation work in this case or is that more work?

**Comment by pauladkisson** [comment]
> Interesting. Would using a different environment for local vs remote installation work in this case or is that more work?

I think that would just end up being more work tbh.

**Pull request closed without merging**
